add_newline = false

[line_break]
disabled = true

[package]
disabled = false

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true
